openapi: 3.0.1
info:
  title: Create User API
  version: 1.0.0

paths:
  /users:
    post:
      summary: Create users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UsersRequest"
      responses:
        '200':
          description: This API is used to create a new user for website
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UsersResponse"

components:
  schemas:
    UsersRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        mobileNumber:
          type: string
    UsersResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: string
        responseCode:
          type: string
